name: WateredDownMusic
favicon: null
layout_spectrum: 0.31429
typography_spectrum: 0.19684
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#739fa0'
    - '#d8d9d1'
    - '#4c3434'
    - '#d88482'
    - '#7f6f6e'
  brandStrength: 0.8125
  lightness: 0.9863539568614215
  saturation: 0.75
  rhythmicContrast: 0.7833295178133994
purpose: []
