name: WateredDownMusic
favicon: null
layout_spectrum: 0.8250433537177742
typography_spectrum: 0.16827411809936166
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6812630263157189
  lightness: 0.9863539568614215
  saturation: 0.6835204444359988
  rhythmicContrast: 0.7833295178133994
purpose: []
